"""Report rendering for RepoPulse."""

from __future__ import annotations

import json
from typing import Iterable, List

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from repopulse.models import CheckResult, CheckStatus, HealthReport


STATUS_ICONS = {
    CheckStatus.PASS: "PASS",
    CheckStatus.WARN: "WARN",
    CheckStatus.FAIL: "FAIL",
}


def render_terminal(report: HealthReport, console: Console | None = None) -> None:
    """Print a rich terminal report."""

    console = console or Console()
    title = Text("RepoPulse Health Report", style="bold")
    subtitle = (
        f"Project: {report.profile.name} | Type: {report.profile.project_type} | "
        f"Score: {report.score}/100 | Grade: {report.grade}"
    )
    console.print(Panel(subtitle, title=title, border_style=_score_style(report.score)))

    table = Table(show_header=True, header_style="bold")
    table.add_column("Status", width=8)
    table.add_column("Check")
    table.add_column("Category", width=16)
    table.add_column("Points", justify="right", width=9)
    table.add_column("Message")

    for result in report.results:
        table.add_row(
            STATUS_ICONS[result.status],
            result.name,
            result.category,
            f"{result.points}/{result.max_points}",
            result.message,
            style=_status_style(result.status),
        )

    console.print(table)

    if report.recommendations:
        console.print("\n[bold]Suggestions[/bold]")
        for recommendation in report.recommendations:
            console.print(f"- {recommendation}")


def to_markdown(report: HealthReport) -> str:
    """Render a health report as Markdown."""

    lines: List[str] = [
        "# RepoPulse Report",
        "",
        f"**Project:** `{report.profile.name}`",
        f"**Type:** {report.profile.project_type}",
        f"**Score:** {report.score}/100",
        f"**Grade:** {report.grade}",
        f"**Generated:** {report.generated_at.isoformat()}",
        "",
        "## Summary",
        "",
        f"- Passed: **{report.passed_count}**",
        f"- Warnings: **{report.warning_count}**",
        f"- Failed: **{report.failed_count}**",
        f"- Total checks: **{len(report.results)}**",
        "",
        "## Checks",
        "",
        "| Status | Check | Category | Points | Result |",
        "| --- | --- | --- | ---: | --- |",
    ]

    for result in report.results:
        lines.append(
            "| "
            f"{_markdown_status(result.status)} | "
            f"{result.name} | "
            f"{result.category} | "
            f"{result.points}/{result.max_points} | "
            f"{_escape_pipe(result.message)} |"
        )

    if report.recommendations:
        lines.extend(["", "## Suggestions", ""])
        for recommendation in report.recommendations:
            lines.append(f"- {recommendation}")

    lines.extend(
        [
            "",
            "## Repository Metadata",
            "",
            f"- Files scanned: **{report.profile.files_count}**",
            f"- Directories scanned: **{report.profile.directories_count}**",
            f"- Root files: `{', '.join(report.profile.detected_files) or 'none'}`",
            "",
            "---",
            "",
            "Generated by [RepoPulse](https://github.com/n-vim/repo-pulse).",
            "",
        ]
    )
    return "\n".join(lines)


def to_json(report: HealthReport, pretty: bool = True) -> str:
    """Render a health report as JSON."""

    indent = 2 if pretty else None
    return json.dumps(report.to_dict(), indent=indent, sort_keys=True)


def write_report(report: HealthReport, output: str, fmt: str) -> None:
    """Write a rendered report to disk."""

    content = to_markdown(report) if fmt == "markdown" else to_json(report)
    with open(output, "w", encoding="utf-8") as file:
        file.write(content)


def _score_style(score: int) -> str:
    if score >= 80:
        return "green"
    if score >= 60:
        return "yellow"
    return "red"


def _status_style(status: CheckStatus) -> str:
    if status == CheckStatus.PASS:
        return "green"
    if status == CheckStatus.WARN:
        return "yellow"
    return "red"


def _markdown_status(status: CheckStatus) -> str:
    if status == CheckStatus.PASS:
        return "PASS"
    if status == CheckStatus.WARN:
        return "WARN"
    return "FAIL"


def _escape_pipe(value: str) -> str:
    return value.replace("|", "\\|")


def summarize_reports(reports: Iterable[HealthReport]) -> str:
    """Return a compact text summary for multiple reports."""

    report_list = list(reports)
    if not report_list:
        return "No reports generated."

    average = round(sum(report.score for report in report_list) / len(report_list))
    best = max(report_list, key=lambda report: report.score)
    worst = min(report_list, key=lambda report: report.score)
    return (
        f"Scanned {len(report_list)} repositories. "
        f"Average score: {average}/100. "
        f"Best: {best.profile.name} ({best.score}). "
        f"Lowest: {worst.profile.name} ({worst.score})."
    )
